version: 0.0

os: linux

files:
  - source: content
    destination: /var/www/html/
  - source: scripts/user_clean.sh
    destination: /home/ubuntu/
  - source: files
    destination: /var/www/files/

permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/files
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/html/content/Uploads
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/html/content/Uploads/Reports
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory

hooks:
  ApplicationStop:
    - location: scripts/1-appstop.sh
      timeout: 512
  BeforeInstall:
    - location: scripts/3-before.sh
      timeout: 512
  AfterInstall:
    - location: scripts/5-after.sh
      timeout: 32
  ApplicationStart:
    - location: scripts/6-appstart.sh
      timeout: 32

