version: 0.0

os: linux

files:
  - source: content
    destination: /var/www/html
  - source: netpivot_kernel
    destination: /opt/netpivot_kernel

permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /opt/netpivot_kernel
    owner: www-data
    group: www-data
    mode: 644
    type: 
      - directory
  - object: /opt/netpivot_kernel
    owner: www-data
    group: www-data
    mode: 755
    type: 
      - file

hooks:
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 256
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 1024
  AfterInstall:
    - location: scripts/after.sh
      timeout: 32
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 32

