version: 0.0

os: linux

files:
  - source: content
    destination: /var/www/html
  - source: netpivot_kernel/f5conv
    destination: /var/www/html/dashboard/
  - source: scripts/user_clean.sh
    destination: /home/ubuntu/

permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory

hooks:
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 512
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 512
  AfterInstall:
    - location: scripts/after.sh
      timeout: 32
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 32

