version: 0.0

os: linux

files:
  - source: content
    destination: /var/www/html

permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory

hooks:
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 64
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 512
  AfterInstall:
    - location: scripts/after.sh
      timeout: 32
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 32

